version: '3.8'

services:
  hinglish-voice-app-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hinglish-voice-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      # Mount source code for development (hot reload)
      - ./app:/app/app
      - ./static:/app/static
      - ./server.py:/app/server.py
      # Persist data
      - ./generated:/app/generated
      - ./voices:/app/voices
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./models:/app/models
    restart: unless-stopped
    command: >
      sh -c "pip install watchdog &&
             python -m uvicorn app.websocket_server:app 
             --host 0.0.0.0 
             --port 8000 
             --reload 
             --reload-dir /app/app 
             --reload-dir /app/static"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: hinglish-voice-dev-network
